version: "3"
services:
  api_service:
    build: .
    image: spring_boot_app:11-jdk-slim
    container_name: springboot
    restart: always
    ports: 
      - 8080:8080
    depends_on:
      - mysqldb
  mysqldb:
    image: "mysql:8.0.33-debian"
    container_name: mysqldb
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: school
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - mysqldata:/var/lib/mysql
volumes:
  mysqldata:
